package com.ericsson.eniq.events.ui.server.config;

public interface ApplicationConfigManager {

    /** Servlet context key */
    String APP_CONFIG_CONTEXT_KEY = "config";

    /**
     * Application config property keys
     */
    String ENIQ_EVENTS_LDAP_URI = "ENIQ_EVENTS_LDAP_URI";

    String ENIQ_EVENTS_UI_VERSION = "ENIQ_EVENTS_UI_VERSION";

    String ENIQ_EVENTS_UI_COPYRIGHT = "ENIQ_EVENTS_UI_COPYRIGHT";

    String ENIQ_EVENTS_SERVICES_URI = "ENIQ_EVENTS_SERVICES_URI";

    String ENIQ_EVENTS_REQUEST_TIMEOUT_TIME_IN_MILLISECONDS = "ENIQ_EVENTS_REQUEST_TIMEOUT_TIME_IN_MILLISECONDS";

    String ENIQ_EVENTS_LOCK_USERS = "ENIQ_EVENTS_LOCK_USERS";

    String ENIQ_EVENTS_MAX_USER_SESSIONS = "ENIQ_EVENTS_MAX_USER_SESSIONS";

    String ENIQ_EVENTS_BANNER_MESSAGE = "ENIQ_EVENTS_BANNER_MESSAGE";

    String ENIQ_EVENTS_GUI_THEME = "ENIQ_EVENTS_GUI_THEME";

    String ENIQ_EVENTS_SUCCESS_RATIO_LESS_THAN_CUT_OFF_AMBER = "ENIQ_EVENTS_SUCCESS_RATIO_LESS_THAN_CUT_OFF_AMBER";

    String ENIQ_EVENTS_SUCCESS_RATIO_LESS_THAN_CUT_OFF_RED = "ENIQ_EVENTS_SUCCESS_RATIO_LESS_THAN_CUT_OFF_RED";

    String USER_PASSWORD_SESSION_PARAM = "USERPASSWORD";

    String USER_PASSWORD_ENCRYPTED_SESSION_PARAM = "ENCRYPTED_USERPASSWORD";

    String GEO_SERVER_URI = "GEO_SERVER_URI";

    String ENIQ_EVENTS_DASHBOARD_REFRESH_TIME_MINS = "ENIQ_EVENTS_DASHBOARD_REFRESH_TIME_MINS";

    String ENIQ_EVENTS_SUC_RAW = "ENIQ_EVENTS_SUC_RAW";


    /**
     * Max Row JNDI property keys
     */
    String ENIQ_EVENTS_MAX_JSON_RESULT_SIZE = "ENIQ_EVENTS_MAX_JSON_RESULT_SIZE";

    String ENIQ_EVENTS_IMSI_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_IMSI_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_IMSI_CALL_SETUP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_IMSI_CALL_SETUP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_IMSI_CALL_DROP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_IMSI_CALL_DROP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_ACCESS_AREA_CALL_DROP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_ACCESS_AREA_CALL_DROP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_ACCESS_AREA_CALL_SETUP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_ACCESS_AREA_CALL_SETUP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_ENODEB_CALL_DROP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_ENODEB_CALL_DROP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_ENODEB_CALL_SETUP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_ENODEB_CALL_SETUP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_SUBSCRIBER_REOCCURING_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_SUBSCRIBER_REOCCURING_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_CAUSE_CODE_CALL_SETUP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_CAUSE_CODE_CALL_SETUP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_CAUSE_CODE_CALL_DROP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_CAUSE_CODE_CALL_DROP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_TRACKING_AREA_CALL_SETUP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_TRACKING_AREA_CALL_SETUP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_TRACKING_AREA_CALL_DROP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_TRACKING_AREA_CALL_DROP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_TERMINAL_CALL_DROP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_TERMINAL_CALL_DROP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_CFA_TERMINAL_CALL_SETUP_RANKING_COUNT = "ENIQ_EVENTS_LTE_CFA_TERMINAL_CALL_SETUP_RANKING_COUNT";

    String ENIQ_EVENTS_TERMINAL_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_TERMINAL_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_MSC_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_MSC_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_CELL_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_CELL_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_BSC_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_BSC_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_CAUSE_CODE_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_CAUSE_CODE_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_APN_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_APN_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_ENODEB_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_ENODEB_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_TERMINAL_GROUP_ANALYSIS_COUNT = "ENIQ_EVENTS_TERMINAL_GROUP_ANALYSIS_COUNT";

    String ENIQ_EVENTS_UNANSWERED_CALLS_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_UNANSWERED_CALLS_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_DURATION_CALLS_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_DURATION_CALLS_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_TERMINAL_ANALYSIS_COUNT = "ENIQ_EVENTS_TERMINAL_ANALYSIS_COUNT";

    String ENIQ_EVENTS_RNC_EVENT_FAILURE_RANKING_COUNT = "ENIQ_EVENTS_RNC_EVENT_FAILURE_RANKING_COUNT";

    String ENIQ_EVENTS_SUBBI_COUNT = "ENIQ_EVENTS_SUBBI_COUNT";

    String ENIQ_EVENTS_PDP_STATISTICS_COUNT = "ENIQ_EVENTS_PDP_STATISTICS_COUNT";

    String ENIQ_EVENTS_LIVE_LOAD_COUNT = "ENIQ_EVENTS_LIVE_LOAD_COUNT";

    String ENIQ_EVENTS_ROAMING_ANALYSIS_COUNT = "ENIQ_EVENTS_ROAMING_ANALYSIS_COUNT";

    String ENIQ_EVENTS_DATA_VOLUME_RANKING_COUNT = "ENIQ_EVENTS_DATA_VOLUME_RANKING_COUNT";

    //LTE HFA Constants

    String ENIQ_EVENTS_LTE_HFA_SUBSCRIBER_EXEC_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_SUBSCRIBER_EXEC_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_SUBSCRIBER_PREP_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_SUBSCRIBER_PREP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_ENODEB_EXEC_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_ENODEB_EXEC_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_ENODEB_PREP_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_ENODEB_PREP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_SOURCE_CELL_EXEC_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_SOURCE_CELL_EXEC_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_SOURCE_CELL_PREP_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_SOURCE_CELL_PREP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_TARGET_CELL_EXEC_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_TARGET_CELL_EXEC_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_TARGET_CELL_PREP_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_TARGET_CELL_PREP_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_CAUSE_CODE_EXEC_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_CAUSE_CODE_EXEC_RANKING_COUNT";

    String ENIQ_EVENTS_LTE_HFA_CAUSE_CODE_PREP_RANKING_COUNT = "ENIQ_EVENTS_LTE_HFA_CAUSE_CODE_PREP_RANKING_COUNT";

    /** JNDI name for repository database */
    String DWHREP_DATA_SOURCE_JNDI_NAME = "dwhrep/jdbc/eniqPool";

    //    String DWHREP_DATA_SOURCE_JNDI_NAME = "jdbc/MySQL";

    /** JNDI name for application properties object */
    String ENIQ_EVENTS_JNDI_NAME = "Eniq_Event_Properties";

    /**
     * Application version info
     * @return version string
     */
    String getEniqEventsAppVersion();

    /**
     * Application copyright message
     * @return copyright message
     */
    String getEniqEventsAppCopyright();

    /**
     * Bootstrap URL for UI metadata
     * @return uri
     */
    String getEniqEventsServicesURI();

    /**
     * @return "code amber" threshold for Success Ratio (usually less than 97)
     */
    float getKPIThresholdAmber();

    /**
     * @return "code red" threshold for Success Ratio (usually less than 95)
     */
    float getKPIThresholdRed();

    /**
     * Get time after midnite (after Aggregation is finished) to set 
     * previous days data selectable on the dashboard and schedule a refresh
     * if user looking at latest enabled data
     * 
     * @return  minutes from midnite to start staggering dashboard 
     *          refreshes (stagger over a range to all UIs don't hit server at same time)
     */
    int getStartDashBoardRefeshMinsFromMidnite();

    /**
     * Get LDAP uri
     * @return uri
     */
    String getLdapURI();

    /**
     * How long should Ajax requests hang run
     * @return timeout in ms
     */
    String getEniqEventsRequestTime();

    /**
     * The Theme to apply to the UI
     * @return
     */
    String getEniqEventsTheme();

    /**
     * Get UI banner message
     * @return
     */
    String getBannerMessage();

    /**
     * Get JNDI Parameter
     * @return
     */
    String getJNDIValue(final String key);

    /**
     * Global user session lock out flag
     * @return true if set false otherwise
     */
    boolean lockoutUsers();

    /**
     * Get max user sessions property.
     * @return max user sessions from config db or default to MAX_USER_SESSIONS if invalid value
     */
    int getMaxUserSessions();

}